### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by stefanoperone** [Viphor/cpn2pn#1]
Hi,
I'm Stefano and  I would like to ask you a question. 
I folllowed your instructions, but I have this error:

$ python3 convertCPN.py -v '/home/perone/Documenti/Example.pnml' 
Traceback (most recent call last):
  File "convertCPN.py", line 111, in <module>
    commands[arg]()
KeyError: '/home/perone/Documenti/Example.pnml'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "convertCPN.py", line 113, in <module>
    run()
  File "convertCPN.py", line 32, in run
    cpn = CPNModel(sys.argv[len(sys.argv) - 1])
  File "/home/perone/Documenti/cpn2pn-master/CPNParser/CPNModel.py", line 225, in init
    self.__parse_types()
  File "/home/perone/Documenti/cpn2pn-master/CPNParser/CPNModel.py", line 235, in __parse_types
    for decl in decls:
TypeError: 'NoneType' object is not iterable

Is it possible that the problem is .PNML file? What is the tool that you used to generate the CPN?
Best reguards,
Stefano.

**Comment by Viphor** [comment]
Could you send your PNML file?
The tool has currently only been tested on the files from the [MCC competition](https://mcc.lip6.fr/2017/)

**Comment by stefanoperone** [comment]
I attached the PNML file.
I would like to use the TINA tool (http://projects.laas.fr/tina//, a tool for Time Petri Nets Analyzer) to generate the state class graph.
But this tool does not support CPN. For this reason I wanted to test your algorithm.

Best regards.
Stefano


Il giorno 22 feb 2018, alle ore 12:57, Viphor <notifications@github.com<mailto:notifications@github.com>> ha scritto:


Could you send your PNML file?
The tool has currently only been tested on the files from the MCC competition<https://mcc.lip6.fr/2017/>

**Comment by Viphor** [comment]
I am unable to see any attachments. Are you able to upload it to gist or something similar?

**Comment by stefanoperone** [comment]
You can download my PNML file from this dropbox link:

https://www.dropbox.com/s/i9yka57xeq4oa8n/CPN.pnml?dl=0

Could you send your PNML file? In this way I can generate the pnml file using code.

**Comment by Viphor** [comment]
I can see that it is built on another syntax than my engine. I follow the PNML standard for [symmetric nets](http://www.pnml.org/version-2009/grammar/symmetricnet.pntd) where colors are declared in /pnml/net/declaration/ and initial markings are defined in hlinitialMarking children. More information on the standard can be found [here](http://www.pnml.org/papers/pnnl76.pdf)
Hopefully this helps.

Best regards
Andreas
